"""add embeddings to document chunks

Revision ID: 80b5d2320c22
Revises: 57e5781b1c97
Create Date: 2026-10-09 12:23:54.602682

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import pgvector


# revision identifiers, used by Alembic.
revision: str = '80b5d2320c22'
down_revision: Union[str, None] = '57e5781b1c97'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
